# Generated by Django 5.2.17 on 2026-09-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_role",
            field=models.CharField(
                blank=True,
                choices=[("client", "Looking for a fundi"), ("fundi", "I am a fundi")],
                max_length=10,
            ),
        ),
    ]
