# Generated by Django 5.2.17 on 2026-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_onboarding_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="portrait",
            field=models.ImageField(blank=True, editable=False, upload_to="portraits/"),
        ),
    ]
