# Generated by Django 5.2.17 on 2026-09-29 06:24

import apps.verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(
                        help_text="Name exactly as printed on the ID.", max_length=150
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("nida_number_encrypted", models.TextField(editable=False)),
                (
                    "nida_number_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("nida_last4", models.CharField(editable=False, max_length=4)),
                (
                    "id_front_image",
                    models.ImageField(
                        storage=apps.verification.models.private_storage,
                        upload_to=apps.verification.models.document_upload_path,
                    ),
                ),
                (
                    "id_back_image",
                    models.ImageField(
                        blank=True,
                        storage=apps.verification.models.private_storage,
                        upload_to=apps.verification.models.document_upload_path,
                    ),
                ),
                (
                    "selfie_image",
                    models.ImageField(
                        storage=apps.verification.models.private_storage,
                        upload_to=apps.verification.models.document_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded by a newer approval"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("manual_review", "Manual review"),
                            ("nida_api", "NIDA API"),
                        ],
                        default="manual_review",
                        max_length=20,
                    ),
                ),
                ("is_duplicate_nida", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unreadable", "Photo unclear or unreadable"),
                            ("details_mismatch", "Details don't match the ID card"),
                            ("face_mismatch", "Selfie doesn't match the ID photo"),
                            ("invalid_document", "Not a valid NIDA card"),
                            (
                                "duplicate_identity",
                                "ID already used by another account",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, help_text="Internal note; not shown to the user."
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="verification.identityverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="identityverification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="one_pending_verification_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="identityverification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("nida_number_hash",),
                name="one_approved_verification_per_nida",
            ),
        ),
    ]
