# Generated by Django 5.2.17 on 2026-09-30 07:45

import apps.verification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="identityverification",
            name="one_approved_verification_per_nida",
        ),
        migrations.RenameField(
            model_name="identityverification",
            old_name="nida_last4",
            new_name="document_last4",
        ),
        migrations.RenameField(
            model_name="identityverification",
            old_name="nida_number_encrypted",
            new_name="document_number_encrypted",
        ),
        migrations.RenameField(
            model_name="identityverification",
            old_name="nida_number_hash",
            new_name="document_number_hash",
        ),
        migrations.RenameField(
            model_name="identityverification",
            old_name="is_duplicate_nida",
            new_name="is_duplicate_document",
        ),
        migrations.AddField(
            model_name="identityverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("nida", "NIDA card"),
                    ("driving_licence", "Driving licence"),
                    ("passport", "Passport"),
                ],
                default="nida",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="portrait",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=apps.verification.models.portrait_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="portrait_box",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="portrait_method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unreadable", "Photo unclear or unreadable"),
                    ("details_mismatch", "Details don't match the ID card"),
                    ("face_mismatch", "Selfie doesn't match the ID photo"),
                    ("invalid_document", "Not a valid ID document"),
                    ("no_portrait", "The photo on the document isn't clear"),
                    ("duplicate_identity", "ID already used by another account"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="identityverification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("document_type", "document_number_hash"),
                name="one_approved_verification_per_document",
            ),
        ),
    ]
