# Generated by Django 5.2.17 on 2026-09-29 06:24

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundiProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=120)),
                ("bio", models.TextField(blank=True)),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                ("photo", models.ImageField(blank=True, upload_to="fundis/photos/")),
                (
                    "base_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "service_radius_km",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "area_text",
                    models.CharField(
                        blank=True, help_text="e.g. 'Sinza, near Mori'", max_length=200
                    ),
                ),
                ("ward", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused by fundi"),
                            ("suspended", "Suspended"),
                            ("banned", "Banned"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("completed_jobs_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fundi_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FundiService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed price"),
                            ("hourly", "Per hour"),
                            ("callout", "Call-out fee"),
                            ("quote", "Quote on site"),
                        ],
                        default="quote",
                        max_length=20,
                    ),
                ),
                (
                    "starting_price_tzs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fundi_services",
                        to="catalog.servicecategory",
                    ),
                ),
                (
                    "fundi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="fundis.fundiprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fundi", "category"), name="unique_fundi_category"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("fundi",),
                        name="one_primary_service_per_fundi",
                    ),
                ],
            },
        ),
    ]
