# Generated by Django 5.2.17 on 2026-09-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundis", "0002_fundiprofile_avg_response_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundiprofile",
            name="photo",
        ),
    ]
