# Generated by Django 5.2.17 on 2026-09-29 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name_en", models.CharField(max_length=80)),
                ("name_sw", models.CharField(max_length=80)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name used by the apps.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "service categories",
                "ordering": ["sort_order", "name_en"],
            },
        ),
    ]
